version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - lll
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
  settings:
    errcheck:
      check-blank: true
    lll:
      line-length: 120
    revive:
      confidence: 0.8
      severity: warning
      rules:
        - name: errorf
          severity: warning
        - name: context-as-argument
          severity: warning
        - name: exported
          severity: warning
        - name: error-naming
          severity: warning
        - name: increment-decrement
          severity: warning
        - name: receiver-naming
          severity: warning
        - name: superfluous-else
          severity: warning
        - name: useless-break
          severity: warning
        - name: defer
          severity: warning
        - name: identical-branches
          severity: warning
        - name: early-return
          severity: warning
        - name: unnecessary-stmt
          severity: warning
        - name: unreachable-code
          severity: warning
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1019
        - -ST1023
        - -QF1001
        - -QF1011
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
