(column X)
(column Y)
(vanishing c1 (+ X (* 2 Y)))
(vanishing c2 (+ (* 2 Y) X))
(vanishing c3 (+ X Y Y))
(vanishing c4 (+ Y X Y))
(vanishing c5 (+ Y Y X))
(vanishing c6 (+ (* 1 X) Y Y))
(vanishing c7 (+ Y (* 1 X) Y))
(vanishing c8 (+ Y Y (* 1 X)))
